export interface Theme {
  id: string;
  name: string;
  description: string;
  category: string;
  primaryColor: string;
  backgroundColor: string;
  cardColor: string;
  textColor: string;
  mutedTextColor: string;
  accentColor: string;
  borderColor: string;
  inputBackground: string;
  fontFamily: string;
  emoji: string;
}

export const BUILT_IN_THEMES: Record<string, Theme> = {
  minimal: {
    id: "minimal",
    name: "Minimal",
    description: "Clean and professional",
    category: "Startup",
    primaryColor: "#6366f1",
    backgroundColor: "#ffffff",
    cardColor: "#f9fafb",
    textColor: "#111827",
    mutedTextColor: "#6b7280",
    accentColor: "#6366f1",
    borderColor: "#e5e7eb",
    inputBackground: "#ffffff",
    fontFamily: "Inter, sans-serif",
    emoji: "✨",
  },
  dark: {
    id: "dark",
    name: "Dark Mode",
    description: "Easy on the eyes",
    category: "OS",
    primaryColor: "#8b5cf6",
    backgroundColor: "#0f172a",
    cardColor: "#1e293b",
    textColor: "#f1f5f9",
    mutedTextColor: "#94a3b8",
    accentColor: "#a78bfa",
    borderColor: "#334155",
    inputBackground: "#1e293b",
    fontFamily: "Inter, sans-serif",
    emoji: "🌙",
  },
  matrix: {
    id: "matrix",
    name: "Matrix",
    description: "Enter the Matrix",
    category: "Movie",
    primaryColor: "#00ff41",
    backgroundColor: "#0d0208",
    cardColor: "#0a1a0a",
    textColor: "#00ff41",
    mutedTextColor: "#00cc33",
    accentColor: "#39ff14",
    borderColor: "#003300",
    inputBackground: "#050d05",
    fontFamily: '"Courier New", monospace',
    emoji: "🟩",
  },
  sakura: {
    id: "sakura",
    name: "Sakura",
    description: "Cherry blossom dreams",
    category: "Anime",
    primaryColor: "#e91e8c",
    backgroundColor: "#fff0f5",
    cardColor: "#fce4ec",
    textColor: "#880e4f",
    mutedTextColor: "#c2185b",
    accentColor: "#f06292",
    borderColor: "#f8bbd0",
    inputBackground: "#fff8fb",
    fontFamily: "Georgia, serif",
    emoji: "🌸",
  },
  cyberpunk: {
    id: "cyberpunk",
    name: "Cyberpunk",
    description: "Neon future 2077",
    category: "Game",
    primaryColor: "#ffdd00",
    backgroundColor: "#0d0221",
    cardColor: "#160830",
    textColor: "#e0e0e0",
    mutedTextColor: "#a0a0c0",
    accentColor: "#ff006e",
    borderColor: "#7c3aed",
    inputBackground: "#1a0840",
    fontFamily: '"Share Tech Mono", "Courier New", monospace',
    emoji: "⚡",
  },
  ocean: {
    id: "ocean",
    name: "Ocean",
    description: "Calm and serene waves",
    category: "Community",
    primaryColor: "#0284c7",
    backgroundColor: "#f0f9ff",
    cardColor: "#e0f2fe",
    textColor: "#0c4a6e",
    mutedTextColor: "#0369a1",
    accentColor: "#06b6d4",
    borderColor: "#bae6fd",
    inputBackground: "#ffffff",
    fontFamily: "Inter, sans-serif",
    emoji: "🌊",
  },
  nebula: {
    id: "nebula",
    name: "Nebula",
    description: "Deep space vibes",
    category: "Tech",
    primaryColor: "#a855f7",
    backgroundColor: "#030712",
    cardColor: "#0f0620",
    textColor: "#f3e8ff",
    mutedTextColor: "#c084fc",
    accentColor: "#c084fc",
    borderColor: "#4c1d95",
    inputBackground: "#0a0315",
    fontFamily: "Inter, sans-serif",
    emoji: "🔮",
  },
  retro: {
    id: "retro",
    name: "Retro",
    description: "8-bit pixel nostalgia",
    category: "Game",
    primaryColor: "#ff6b35",
    backgroundColor: "#fdf6e3",
    cardColor: "#f5e6c8",
    textColor: "#3c1e00",
    mutedTextColor: "#8b6914",
    accentColor: "#e63946",
    borderColor: "#d4a853",
    inputBackground: "#fef9ed",
    fontFamily: '"Courier New", monospace',
    emoji: "👾",
  },
  dracula: {
    id: "dracula",
    name: "Dracula",
    description: "The iconic dark theme",
    category: "OS",
    primaryColor: "#bd93f9",
    backgroundColor: "#282a36",
    cardColor: "#1e1f29",
    textColor: "#f8f8f2",
    mutedTextColor: "#6272a4",
    accentColor: "#ff79c6",
    borderColor: "#44475a",
    inputBackground: "#21222c",
    fontFamily: "Inter, sans-serif",
    emoji: "🧛",
  },
  naruto: {
    id: "naruto",
    name: "Naruto",
    description: "Believe it! Hidden Leaf vibes",
    category: "Anime",
    primaryColor: "#f97316",
    backgroundColor: "#fefce8",
    cardColor: "#fef9c3",
    textColor: "#1c1917",
    mutedTextColor: "#78350f",
    accentColor: "#dc2626",
    borderColor: "#fed7aa",
    inputBackground: "#ffffff",
    fontFamily: "Inter, sans-serif",
    emoji: "🍃",
  },
  midnight: {
    id: "midnight",
    name: "Midnight",
    description: "Elegant dark with gold",
    category: "Event",
    primaryColor: "#d4af37",
    backgroundColor: "#0a0a0f",
    cardColor: "#12121a",
    textColor: "#f5f5dc",
    mutedTextColor: "#a09070",
    accentColor: "#ffd700",
    borderColor: "#2a2a3a",
    inputBackground: "#0f0f18",
    fontFamily: "Georgia, serif",
    emoji: "🌙",
  },
  startup: {
    id: "startup",
    name: "Startup",
    description: "Move fast, build things",
    category: "Startup",
    primaryColor: "#10b981",
    backgroundColor: "#f8fafc",
    cardColor: "#ffffff",
    textColor: "#0f172a",
    mutedTextColor: "#64748b",
    accentColor: "#06b6d4",
    borderColor: "#e2e8f0",
    inputBackground: "#ffffff",
    fontFamily: "Inter, sans-serif",
    emoji: "🚀",
  },
  dexter: {
    id: "dexter",
    name: "Dexter's Lab",
    description: "90s cartoon genius scientist",
    category: "Cartoon",
    primaryColor: "#cc0000",
    backgroundColor: "#e8f0fe",
    cardColor: "#ffffff",
    textColor: "#1a1a2e",
    mutedTextColor: "#5c5c8a",
    accentColor: "#cc0000",
    borderColor: "#b0c4f8",
    inputBackground: "#f0f4ff",
    fontFamily: '"Courier New", monospace',
    emoji: "🧪",
  },
};

export function getTheme(id: string): Theme {
  return BUILT_IN_THEMES[id] ?? BUILT_IN_THEMES["minimal"]!;
}

export function getThemeList(): Theme[] {
  return Object.values(BUILT_IN_THEMES);
}
